# Generated by Django 4.0.4 on 2023-10-17 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_image_productmodel_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='img',
            new_name='image',
        ),
    ]
