# Generated by Django 4.2.6 on 2023-10-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_img_productmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='product_amount',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
