# Generated by Django 4.0.4 on 2023-10-18 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_delete_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormModel',
        ),
        migrations.AlterModelOptions(
            name='productmodel',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='product_amount',
        ),
    ]
